/*
copyright (C) 2011 by high828@gmail.com

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoLNotes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoLNotes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap circle_green {
            get {
                object obj = ResourceManager.GetObject("circle_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap circle_red {
            get {
                object obj = ResourceManager.GetObject("circle_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap circle_yellow {
            get {
                object obj = ResourceManager.GetObject("circle_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[
        ///{
        ///&quot;k&quot;:1058,
        ///&quot;v&quot;:
        ///{
        ///	&quot;Name&quot;:&quot;Needlessly Large Rod&quot;,
        ///	&quot;Description&quot;:&quot;+80 Ability Power&quot;
        ///}
        ///},
        ///{
        ///&quot;k&quot;:1057,
        ///&quot;v&quot;:
        ///{
        ///&quot;Name&quot;:&quot;Negatron Cloak&quot;,
        ///&quot;Description&quot;:&quot;+48 Magic Resist&quot;
        ///}
        ///},
        ///{
        ///&quot;k&quot;:1056,
        ///&quot;v&quot;:
        ///{
        ///&quot;Name&quot;:&quot;Doran\\&apos;s Ring&quot;,
        ///&quot;Description&quot;:&quot;+100 Health +15 Ability Power +5 Mana Regen per 5 seconds&quot;
        ///}
        ///},
        ///{
        ///&quot;k&quot;:1055,
        ///&quot;v&quot;:
        ///{
        ///&quot;Name&quot;:&quot;Doran\\&apos;s Blade&quot;,
        ///&quot;Description&quot;:&quot;+100 Health +10 Attack Damage +3% Life Steal&quot;
        ///}
        ///},
        ///{
        ///&quot;k&quot;:1054,
        ///&quot;v&quot;:
        ///{
        ///&quot;Name&quot;:&quot;Doran\\&apos;s Shield&quot;,
        ///&quot;Description&quot;:&quot;+1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemData {
            get {
                return ResourceManager.GetString("ItemData", resourceCulture);
            }
        }
        
        internal static byte[] LolLoader {
            get {
                object obj = ResourceManager.GetObject("LolLoader", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
