//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoLNotes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoLNotes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;1&quot;:&quot;Annie&quot;,
        ///	&quot;2&quot;:&quot;Olaf&quot;,
        ///	&quot;3&quot;:&quot;Galio&quot;,
        ///	&quot;4&quot;:&quot;TwistedFate&quot;,
        ///	&quot;5&quot;:&quot;XinZhao&quot;,
        ///	&quot;6&quot;:&quot;Urgot&quot;,
        ///	&quot;7&quot;:&quot;Leblanc&quot;,
        ///	&quot;8&quot;:&quot;Vladimir&quot;,
        ///	&quot;9&quot;:&quot;FiddleSticks&quot;,
        ///	&quot;10&quot;:&quot;Kayle&quot;,
        ///	&quot;11&quot;:&quot;MasterYi&quot;,
        ///	&quot;12&quot;:&quot;Alistar&quot;,
        ///	&quot;13&quot;:&quot;Ryze&quot;,
        ///	&quot;14&quot;:&quot;Sion&quot;,
        ///	&quot;15&quot;:&quot;Sivir&quot;,
        ///	&quot;16&quot;:&quot;Soraka&quot;,
        ///	&quot;17&quot;:&quot;Teemo&quot;,
        ///	&quot;18&quot;:&quot;Tristana&quot;,
        ///	&quot;19&quot;:&quot;Warwick&quot;,
        ///	&quot;20&quot;:&quot;Nunu&quot;,
        ///	&quot;21&quot;:&quot;MissFortune&quot;,
        ///	&quot;22&quot;:&quot;Ashe&quot;,
        ///	&quot;23&quot;:&quot;Tryndamere&quot;,
        ///	&quot;24&quot;:&quot;Jax&quot;,
        ///	&quot;25&quot;:&quot;Morgana&quot;,
        ///	&quot;26&quot;:&quot;Zilean&quot;,
        ///	&quot;27&quot;:&quot;Singed&quot;,
        ///	&quot;28&quot;:&quot;Evelynn&quot;,
        ///	&quot;29&quot;:&quot;Twitch&quot;,
        ///	&quot;30&quot;:&quot;Karth [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChampData {
            get {
                return ResourceManager.GetString("ChampData", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap circle_green {
            get {
                object obj = ResourceManager.GetObject("circle_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap circle_red {
            get {
                object obj = ResourceManager.GetObject("circle_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap circle_yellow {
            get {
                object obj = ResourceManager.GetObject("circle_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[
        ///{
        ///&quot;k&quot;:1058,
        ///&quot;v&quot;:
        ///{
        ///	&quot;Name&quot;:&quot;Needlessly Large Rod&quot;,
        ///	&quot;Description&quot;:&quot;+80 Ability Power&quot;
        ///}
        ///},
        ///{
        ///&quot;k&quot;:1057,
        ///&quot;v&quot;:
        ///{
        ///&quot;Name&quot;:&quot;Negatron Cloak&quot;,
        ///&quot;Description&quot;:&quot;+48 Magic Resist&quot;
        ///}
        ///},
        ///{
        ///&quot;k&quot;:1056,
        ///&quot;v&quot;:
        ///{
        ///&quot;Name&quot;:&quot;Doran\\&apos;s Ring&quot;,
        ///&quot;Description&quot;:&quot;+100 Health +15 Ability Power +5 Mana Regen per 5 seconds&quot;
        ///}
        ///},
        ///{
        ///&quot;k&quot;:1055,
        ///&quot;v&quot;:
        ///{
        ///&quot;Name&quot;:&quot;Doran\\&apos;s Blade&quot;,
        ///&quot;Description&quot;:&quot;+100 Health +10 Attack Damage +3% Life Steal&quot;
        ///}
        ///},
        ///{
        ///&quot;k&quot;:1054,
        ///&quot;v&quot;:
        ///{
        ///&quot;Name&quot;:&quot;Doran\\&apos;s Shield&quot;,
        ///&quot;Description&quot;:&quot;+1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemData {
            get {
                return ResourceManager.GetString("ItemData", resourceCulture);
            }
        }
        
        internal static byte[] LolLoader {
            get {
                object obj = ResourceManager.GetObject("LolLoader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] prod_eu_lol_riotgames_com {
            get {
                object obj = ResourceManager.GetObject("prod_eu_lol_riotgames_com", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] prod_eun1_lol_riotgames_com {
            get {
                object obj = ResourceManager.GetObject("prod_eun1_lol_riotgames_com", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] prod_na1_lol_riotgames_com {
            get {
                object obj = ResourceManager.GetObject("prod_na1_lol_riotgames_com", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;WIN&quot;:&quot;Victories&quot;,
        ///	&quot;CHAMPIONS_KILLED&quot;:&quot;Champion Kills&quot;,
        ///	&quot;TOTAL_ASSISTS&quot;:&quot;Assists&quot;,
        ///	&quot;FRIENDLY_HQ_LOST&quot;:&quot;Friendly Nexus Destroyed&quot;,
        ///	&quot;TOTAL_TIMES_SPELL4_CAST&quot;:&quot;Spell 4 Casts&quot;,
        ///	&quot;UNREAL_KILLS&quot;:&quot;Unreal Kills&quot;,
        ///	&quot;MAX_CHAMPIONS_KILLED&quot;:&quot;Max Kills&quot;,
        ///	&quot;TOTAL_PLAYER_SCORE&quot;:&quot;Total Score&quot;,
        ///	&quot;SPELL2_CAST&quot;:&quot;Spell 2 Casts&quot;,
        ///	&quot;TOTAL_CHAMPION_KILLS&quot;:&quot;Total Champion Kills&quot;,
        ///	&quot;EXP&quot;:&quot;Champion Experience&quot;,
        ///	&quot;MINIONS_KILLED&quot;:&quot;Minions Slain&quot;,
        ///	&quot;MAGIC_DAMAGE_TAKEN&quot;:&quot;Magic Damage Taken&quot;,
        ///	&quot;SUPER_MONSTER_KILLED&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatsData {
            get {
                return ResourceManager.GetString("StatsData", resourceCulture);
            }
        }
    }
}
