<?xml version="1.0" encoding="utf-8"?><Database Class="LoLNotesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="Games">
    <Type Name="Games">
      <Column Name="GameId" Type="System.Int64" IsPrimaryKey="true" CanBeNull="false" />
      <Column Member="GameLength" Type="System.Int32" CanBeNull="false" />
      <Column Name="" Member="RawData" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>