<?xml version="1.0" encoding="utf-8"?><Database Class="LoLNotesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="Class1s">
    <Type Name="Class1">
      <Column Member="GameId" Type="System.Int64" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>